# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sucursal.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'sucursal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esucursal.proto\x12\x08sucursal\"H\n\x08Sucursal\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x03 \x01(\x05\x12\x0e\n\x06precio\x18\x04 \x01(\x02\"\x07\n\x05Vacio\"9\n\x0fListaSucursales\x12&\n\nsucursales\x18\x01 \x03(\x0b\x32\x12.sucursal.Sucursal\"A\n\rNuevaSucursal\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x02 \x01(\x05\x12\x0e\n\x06precio\x18\x03 \x01(\x02\"(\n\tResultado\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t2\x94\x01\n\x10ServicioSucursal\x12?\n\x11ObtenerSucursales\x12\x0f.sucursal.Vacio\x1a\x19.sucursal.ListaSucursales\x12?\n\x0f\x41gregarSucursal\x12\x17.sucursal.NuevaSucursal\x1a\x13.sucursal.Resultadob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sucursal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUCURSAL']._serialized_start=28
  _globals['_SUCURSAL']._serialized_end=100
  _globals['_VACIO']._serialized_start=102
  _globals['_VACIO']._serialized_end=109
  _globals['_LISTASUCURSALES']._serialized_start=111
  _globals['_LISTASUCURSALES']._serialized_end=168
  _globals['_NUEVASUCURSAL']._serialized_start=170
  _globals['_NUEVASUCURSAL']._serialized_end=235
  _globals['_RESULTADO']._serialized_start=237
  _globals['_RESULTADO']._serialized_end=277
  _globals['_SERVICIOSUCURSAL']._serialized_start=280
  _globals['_SERVICIOSUCURSAL']._serialized_end=428
# @@protoc_insertion_point(module_scope)
