# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sucursal_pb2 as sucursal__pb2


GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sucursal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServicioSucursalStub(object):
    """Servicio gRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerSucursales = channel.unary_unary(
                '/sucursal.ServicioSucursal/ObtenerSucursales',
                request_serializer=sucursal__pb2.Vacio.SerializeToString,
                response_deserializer=sucursal__pb2.ListaSucursales.FromString,
                _registered_method=True)
        self.AgregarSucursal = channel.unary_unary(
                '/sucursal.ServicioSucursal/AgregarSucursal',
                request_serializer=sucursal__pb2.NuevaSucursal.SerializeToString,
                response_deserializer=sucursal__pb2.Resultado.FromString,
                _registered_method=True)


class ServicioSucursalServicer(object):
    """Servicio gRPC
    """

    def ObtenerSucursales(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgregarSucursal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicioSucursalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerSucursales': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerSucursales,
                    request_deserializer=sucursal__pb2.Vacio.FromString,
                    response_serializer=sucursal__pb2.ListaSucursales.SerializeToString,
            ),
            'AgregarSucursal': grpc.unary_unary_rpc_method_handler(
                    servicer.AgregarSucursal,
                    request_deserializer=sucursal__pb2.NuevaSucursal.FromString,
                    response_serializer=sucursal__pb2.Resultado.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sucursal.ServicioSucursal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sucursal.ServicioSucursal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicioSucursal(object):
    """Servicio gRPC
    """

    @staticmethod
    def ObtenerSucursales(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sucursal.ServicioSucursal/ObtenerSucursales',
            sucursal__pb2.Vacio.SerializeToString,
            sucursal__pb2.ListaSucursales.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgregarSucursal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sucursal.ServicioSucursal/AgregarSucursal',
            sucursal__pb2.NuevaSucursal.SerializeToString,
            sucursal__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
